changelog:
  categories:
    - title: "New Features"
      labels: ["type: feature"]
    - title: "Bug Fixes"
      labels: ["type: bug"]
    - title: "Security"
      labels: ["security"]
    - title: "Improvements"
      labels: ["type: enhancement"]
    - title: "Documentation"
      labels: ["type: docs"]
    - title: "Maintenance"
      labels: ["infra", "type: refactor"]
  exclude:
    labels: ["duplicate", "invalid", "wontfix"]
